services:
  postgres:
    image: postgres:15
    container_name: task_manager_pro-db
    restart: always
    environment:
      POSTGRES_DB: task_manager_pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: task-manager-pro
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_manager_pro
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret123
    depends_on:
      - postgres
volumes:
  pgdata: {}