spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_manager_pro
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

server:
  port: 8080

jwt:
  expiration: 86400000
